server:
  port: 8072

logging:
  level:
    com:
      bank:
        gatewayserver: DEBUG

spring:
  application:
    name: gatewayserver
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

endpoints:
  shutdown:
    enabled: true

management:
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Gateway Server Microservice"
    version: 1.0.0
    description: "Bank Gateway Server Microservice"


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/