server:
  port: 8070

spring:
  application:
    name: "eurekaserver"
  profiles:
    active: default
  config:
    import: optional:configserver:http://localhost:8071

  cloud:
    loadbalancer:
      ribbon:
        enable: false

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"